### ISSUE TITLE
TypeError: browserVersion.split is not a function

### ISSUE THREAD

**Issue by th0rgall** [rubenspgcavalcante/webpack-chrome-extension-reloader#87]
**Type:**
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] question

**Environment:**
 - OS: macOS 10.14.3
 - Library Version: 1.2.0

**I'm going to open a PR:**
- [ ] yes
- [x] no

**Description:**
I get the following error after webpack compilation:
```
/Users/thor/Webdev/vocadder/browser-extension/node_modules/webpack-chrome-extension-reloader/dist/webpack:/src/hot-reload/SignEmitter.ts:60
      browserVersion.split(".").map(n => parseInt(n)),
                     ^
TypeError: browserVersion.split is not a function
    at SignEmitter._satisfies (/Users/thor/Webdev/vocadder/browser-extension/node_modules/webpack-chrome-extension-reloader/dist/webpack:/src/hot-reload/SignEmitter.ts:60:22)
    at new SignEmitter (/Users/thor/Webdev/vocadder/browser-extension/node_modules/webpack-chrome-extension-reloader/dist/webpack:/src/hot-reload/SignEmitter.ts:21:54)
    at WebSocketServer.<anonymous> (/Users/thor/Webdev/vocadder/browser-extension/node_modules/webpack-chrome-extension-reloader/dist/webpack:/src/hot-reload/HotReloaderServer.ts:16:26)
    at WebSocketServer.emit (events.js:197:13)
    at handleUpgrade (/Users/thor/Webdev/vocadder/browser-extension/node_modules/ws/lib/websocket-server.js:86:18)
    at WebSocketServer.completeUpgrade (/Users/thor/Webdev/vocadder/browser-extension/node_modules/ws/lib/websocket-server.js:312:5)
    at WebSocketServer.handleUpgrade (/Users/thor/Webdev/vocadder/browser-extension/node_modules/ws/lib/websocket-server.js:236:10)
    at Server.upgrade (/Users/thor/Webdev/vocadder/browser-extension/node_modules/ws/lib/websocket-server.js:85:16)
    at Server.emit (events.js:197:13)
    at onParserExecuteCommon (_http_server.js:554:14)
    at onParserExecute (_http_server.js:501:3)
```

The cause could be that `browserVersion` does not have a default version [here](https://github.com/rubenspgcavalcante/webpack-chrome-extension-reloader/blob/master/src/hot-reload/SignEmitter.ts#L58), while it has at [line 19](https://github.com/rubenspgcavalcante/webpack-chrome-extension-reloader/blob/master/src/hot-reload/SignEmitter.ts#L19).

**Comment by rubenspgcavalcante** [comment]
Hey @th0rgall , sorry for the late response (I was on vacations).
Well that's true, need to patch this and make some tests to cover this case, so it don't break again :)

Thanks for the info! \o
